version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 9090:9090
    volumes:
      - .:/app/

  database:
    image: mysql:8.0.28
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: sre_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./tmp/db/data:/var/lib/mysql